DROP SCHEMA journals AUTHORIZATION DBA;
CREATE SCHEMA journals AUTHORIZATION DBA;

create table category (id bigint generated by default as identity (start with 1), name varchar(255) not null, primary key (id));
create table journal (id bigint generated by default as identity (start with 1), name varchar(255) not null, publish_date timestamp not null, uuid varchar(255) not null, category_id bigint not null, publisher_id bigint not null, primary key (id));
create table publisher (id bigint generated by default as identity (start with 1), name varchar(255) not null, user_id bigint not null, primary key (id));
create table subscription (id bigint generated by default as identity (start with 1), date timestamp not null, category_id bigint not null, user_id bigint not null, primary key (id));
create table user (id bigint generated by default as identity (start with 1), enabled boolean not null, login_name varchar(255) not null, pwd varchar(255) not null, role varchar(255) not null, primary key (id));

alter table publisher add constraint UK_ml1xc0aovqkkm2p1lssgjkfas unique (user_id);
alter table journal add constraint FKcas9l8vih6s8sf0xlb6o1s5dh foreign key (category_id) references category;
alter table journal add constraint FKqe1ynobo9ckvg9ocw5spgwf9h foreign key (publisher_id) references publisher;
alter table publisher add constraint FKd1tl2ielb4uyjloqxemfr474e foreign key (user_id) references user;
alter table subscription add constraint FKnj55m79pro2qanuayd9ckn3st foreign key (category_id) references category;
alter table subscription add constraint FK8l1goo02px4ye49xd7wgogxg6 foreign key (user_id) references user;

